version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    #user: "0"
    container_name: mqtt-AID
    restart: unless-stopped
    volumes:
      - mosquittoConfigVolume:/mosquitto/config
      - mosquittoDataVolume:/mosquitto/data
      - mosquittoLogVolume:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    logging:
      options:
        max-file: "5"
        max-size: "10m"

  nodered:
    image: nodered/node-red:latest
    #user: "0"
    container_name: nodered-AID
    environment:
      - TZ=Europe/Vienna
    restart: unless-stopped
    ports:
      - 1880:1880
    volumes:
      - noderedVolume:/data
    logging:
      options:
        max-file: "5"
        max-size: "10m"

  grafana:
    image: grafana/grafana-oss:latest
    #user: "0"
    container_name: grafana-AID
    environment:
      - TZ=Europe/Vienna
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafanaVolume:/var/lib/grafana
    logging:
      options:
        max-file: "5"
        max-size: "10m"
  
  portainer:
    image: portainer/portainer-ce:latest
    #user: "0"
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainerVolume:/data
    ports:
      - 8000:8000
      - 9443:9443
      
  # cse:
  #   container_name: acme-cse-AID
  #   #user: "0"
  #   image: philipp666/cse:v0.2
  #   working_dir: "/opt/ACME-oneM2M-CSE/"
  #   volumes:
  #     - cseVolume:/opt/ACME-oneM2M-CSE
  #   entrypoint: "python3 -m acme"
  #   restart: unless-stopped
  #   ports: 
  #     - 8080:8080

  zigbee2mqtt:
    container_name: zigbee2mqttAID
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - zigbee2mqttVolume:/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Vienna
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyUSB0

volumes:
  mosquittoConfigVolume:
  mosquittoDataVolume:
  mosquittoLogVolume:
  noderedVolume:
  grafanaVolume:
  portainerVolume:
  zigbee2mqttVolume:
  cseVolume: